### ISSUE TITLE
Error when K exceeds 99

### ISSUE THREAD

**Issue by clin045** [rhondabacher/SCnorm#13]
Hey, I'm trying to run SCnorm on my RNA-seq data, and I'm getting the following output:

Gene filter is applied within each condition.
22023 genes were not included in the normalization due to having less 
           than 10 non-zero values.
23497 genes were not included in the normalization due to having less 
           than 10 non-zero values.
26290 genes were not included in the normalization due to having less 
           than 10 non-zero values.
28737 genes were not included in the normalization due to having less 
           than 10 non-zero values.
26609 genes were not included in the normalization due to having less 
           than 10 non-zero values.
19669 genes were not included in the normalization due to having less 
           than 10 non-zero values.
A list of these genes can be accessed in output, 
    see vignette for example.
Finding K for Condition sample1
Trying K = 1
Trying K = 2
Finding K for Condition sample2
Trying K = 1
Trying K = 2
Finding K for Condition sample3
Trying K = 1
Trying K = 2
Finding K for Condition sample4
Trying K = 1
Trying K = 2
Trying K = 3
Trying K = 4
Trying K = 5
Trying K = 6
Trying K = 7
Trying K = 8
Trying K = 9
Trying K = 10
Trying K = 11
Trying K = 12
Trying K = 13
Trying K = 14
Trying K = 15
Trying K = 16
Trying K = 17
Trying K = 18
Trying K = 19
Trying K = 20
Trying K = 21
Trying K = 22
Trying K = 23
Trying K = 24
Trying K = 25
Trying K = 26
Trying K = 27
Trying K = 28
Trying K = 29
Trying K = 30
Trying K = 31
Trying K = 32
Trying K = 33
Trying K = 34
Trying K = 35
Trying K = 36
Trying K = 37
Trying K = 38
Trying K = 39
Trying K = 40
Trying K = 41
Trying K = 42
Trying K = 43
Trying K = 44
Trying K = 45
Trying K = 46
Trying K = 47
Trying K = 48
Trying K = 49
Trying K = 50
Trying K = 51
Trying K = 52
Trying K = 53
Trying K = 54
Trying K = 55
Trying K = 56
Trying K = 57
Trying K = 58
Trying K = 59
Trying K = 60
Trying K = 61
Trying K = 62
Trying K = 63
Trying K = 64
Trying K = 65
Trying K = 66
Trying K = 67
Trying K = 68
Trying K = 69
Trying K = 70
Trying K = 71
Trying K = 72
Trying K = 73
Trying K = 74
Trying K = 75
Trying K = 76
Trying K = 77
Trying K = 78
Trying K = 79
Trying K = 80
Trying K = 81
Trying K = 82
Trying K = 83
Trying K = 84
Trying K = 85
Trying K = 86
Trying K = 87
Trying K = 88
Trying K = 89
Trying K = 90
Trying K = 91
Trying K = 92
Trying K = 93
Trying K = 94
Trying K = 95
Trying K = 96
Trying K = 97
Trying K = 98
Trying K = 99
Error in sreg[[ADDTO]] <- c(sreg[[ADDTO]], sreg[[i]]) : 
  more elements supplied than there are to replace

Any ideas on what could be causing this problem?

**Comment by rhondabacher** [comment]
Hi Christopher,

It looks like SCnorm is failing to converge in choosing the number of groups to normalize. I'm concerned this is due to the number of genes you've listed being filtered out by SCnorm. What is the total size of your dataset (# of genes and samples per condition)?  Also, are you using the default filter or did you add any additional filters?

It might also help if you can send the count-depth plots for your data before normalization. You can do this in SCnorm using the checkCountDepth function:
checkCountDepth(Data, Conditions = Conditions, OutputName="Unnormalized")

Thanks!
Rhonda

**Comment by clin045** [comment]
Rhonda,

There are 29109 genes, and the number of samples are as follows:

- sample1: 1381
- sample2: 472
- sample3: 1896
- sample4: 1298
- sample5: 1076
- sample6: 796

I am using the default filter.

Running checkCountDepth() gives me the following error:
`Error in density.default(na.omit(Slopes[useg])) : 
  need at least 2 points to select a bandwidth automatically`




Thanks,
Christopher

**Comment by rhondabacher** [comment]
Hi Christopher,

Given the number of zeros in your data, it's possible that either there are too few genes passing the filter or the quantile regression is having trouble estimating a slope due to many low count ties.

Can you try the checkCountDepth function again with the option ditherCounts=TRUE ?
(if that works you might also try it in the SCnorm function)

I'm also happy to take a look at the data to further diagnose, specifically the samples for organoid_5FU or xenograft. I'd keep the data private of course, but you can send without gene/samples names if you want. My email is rbacher@wisc.edu

Thanks,
Rhonda

**Comment by clin045** [comment]
Rhonda,

I tried running with ditherCounts=T, but it throws the following error for each of my conditions:

```
Jittering values introduces some randomness, for 
           reproducibility set.seed(1) has been set
Error in density.default(na.omit(Slopes[useg])) : 
  argument 'x' must be numeric
```

Thanks,
Christopher
